### ISSUE TITLE
Meeting moment on Monday: time and place

### ISSUE THREAD

**Issue by mstruijs** [JorisOnGithub/GeometryContest#26]
I recall having scheduled a working session with you tomorrow. Can you inform me of the time you intend to start and the location?

--Martijn
(As this is the most direct channel I have, I'm asking here)

**Comment by JorisOnGithub** [comment]
I don't know, I just asked in our groupchat.

**Comment by mstruijs** [comment]
@JorisOnGithub Please let me know when you've decided on a time and place.

**Comment by JorisOnGithub** [comment]
We will be in the honors room. I will be there in the afternoon, others are already there.
